---
title: "Formation au carroyage et lissage spatial sur R"
author: "Kim Antunez et Julien Pramil"
date: "11 mars 2022"
output:
  prettydoc::html_pretty:
    theme: architect
---

```{r setup, include=FALSE}

# path_proj <- "V:/PSAR-AU/Formation Comment utiliser les outils AU/2022/Séquence 6 - Outils [JP et KA]/tplissage_poc"
# path_lib <- paste0(path_proj,"/packages")

knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_knit$set(root.dir = path_proj)

```

En 2018, le PSAR analyse urbaine, ancêtre de la section analyse urbaine à la direction générale de l'Insee, a développé un package R, nommé `btb` (auteurs : Arlindo Dos Santo et François Sémécurbe).

Sa principale fonction, `kernelSmoothing`, permet de réaliser très facilement un **carroyage** et un **lissage** sur des données géolocalisées avec R. 

À partir de données ponctuelles, nous allons apprendre en utilisant le langage R :

 - À carroyer les informations.
 - À réaliser des lissages de densité, des lissages de moyennes, des lissages de taux et des lissages quantiles.
 - À calculer un indicateur sur une zone à façon à partir des données carroyées de l'Insee.

**Liens utiles**

- Code de la formation : https://github.com/InseeFrLab/formation-r-lissage-spatial

- Site web des supports de formation : https://inseefrlab.github.io/formation-r-lissage-spatial
  * [Tutoriel](tuto.html)
  * [Exercices](exo.html)
