# Workflow derived from https://github.com/r-lib/actions/tree/master/examples 
## Need help debugging build failures ? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [ main ]
    # paths: 
    #   - '**.Rmd'
    #   - '**.qmd'

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-renv@v1
      
    #  - uses: cderv/install-quarto-action@v1
    #  - run: |
    #      quarto --version
      
      - name: Install rmarkdown
        run: |
          Rscript -e 'install.packages(c("remotes"))'
          Rscript -e "install.packages('terra', repos='https://rspatial.r-universe.dev')"
          Rscript -e 'install.packages(c("remotes","rmarkdown","prettydoc","rmdformats","mapview"))' #,"quarto",
          Rscript -e 'install.packages("rgeos", repos="http://R-Forge.R-project.org", type="source")'
          Rscript -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org", type="source")'
          Rscript -e 'install.packages("terra", repos="http://R-Forge.R-project.org", type="source")'
          Rscript -e 'install.packages("sf", type = "mac.binary")'
          Rscript -e "remotes::install_github('koncina/unilur')"
          # Rscript -e "download.file('https://github.com/inseefrlab/formation-r-lissage-spatial/archive/refs/heads/gh-pages.zip',
          #     destfile = 'gh-pages.zip')"
          # Rscript -e "unzip('gh-pages.zip', overwrite = FALSE, exdir='tutorials/', junkpaths = TRUE)"

      
      # - name: Render Quarto files
      #   run: |
      #     Rscript -e "quarto::quarto_render('tutorials/tuto_presentation.qmd')"
      #     #QMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]qmd$'))
      #     #Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) quarto::quarto_render(f)' ${QMD_PATH[*]}

      
      - name: Render Rmarkdown files
        run: |
          #RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          #Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
          Rscript -e "rmarkdown::render('tutorials/index.Rmd')"
          Rscript -e "rmarkdown::render('tutorials/tuto.Rmd')"
          Rscript -e "rmarkdown::render('tutorials/exo.Rmd')"
       
      
      - name: Move files to build directory
        run: |
          mkdir build
          cp -R tutorials/* build
      - name: Push to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
